import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Cards from '../components/cards'
import { Navbar } from '../components/navbar'
import React from 'react';
import Fade from 'react-reveal/Fade';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <main className={styles.main}>
        <div>
            <div className="container flex overflow-y-auto px-6 py-4 mx-auto lg:h-128 lg:py-16">
                <div className="flex flex-col items-center w-full lg:flex-row lg:w-1/2">
                    <div className="max-w-lg">
                        <Fade bottom><h1 className="text-3xl tracking-wide text-gray-800 lg:text-4xl">Set your title</h1></Fade>
                        <p className="mt-4 text-gray-300 text-gray-600">Lorem ipsum, dolor sit amet consectetur
                            adipisicing elit. Aut quia asperiores alias vero magnam recusandae adipisci ad vitae
                            laudantium quod rem voluptatem eos accusantium cumque.</p>
                        <div className="mt-6">
                            <a href="#"
                                className="block px-3 py-2 font-semibold text-center text-white transition-colors duration-200 transform bg-airvisual rounded-md lg:inline hover:bg-blue-400">Download
                            </a>
                        </div>
                    </div>
                </div>

                <div className="flex items-center justify-center w-full h-96 lg:w-1/2">
                    <img className="object-cover w-full h-full max-w-2xl rounded-md"
                        src="https://source.unsplash.com/user/erondu/1600x900" alt="apple watch photo"/>
                </div>
            </div>
        </div>
        

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>

      <Cards />
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
